Repository matyas94/Rajongoi9A-D, pull requests merged in 2024-03, with the labels that each got.

#4 Martin
  assets/favicon.ico
  assets/profile.png
Labels: SZM, ok

#14 .htaccess hozzáadva
  .htaccess
Labels: SZM, ok

#15 orbán odébb tolva
  assets/profile.png
  css/styles.css
Labels: SZM, said nah

#20 favicon hátterének eltüntetése
  assets/favicon.ico
Labels: SZM, ok

#34 alternatív scrollbar
  css/styles.css
Labels: ok, oláh balázs

#36 tökéletesítések
  Magyar/teljesitmenyek.html
Labels: ok
