Repository matyas94/Rajongoi9A-D, pull requests merged in 2024-04, with the labels that each got.

#39 22 kvíz oldal elkezdése
  Magyar/api.json
  Magyar/baratai.html
  Magyar/index.html
  Magyar/kviz.html
  Magyar/teljesitmenyek.html
  assets/quiz.png
  css/style1.css
  css/styles.css
  js/script1.js
Labels: SZM, ok

#57 - sokminden
  English/achievements.html
  English/creators.html
  English/friends.html
  English/mainpage.html
  English/quiz.html
  Magyar/baratai.html
  Magyar/fooldal.html
  Magyar/kviz.html
  Magyar/nevjegy.html
  Magyar/teljesitmenyek.html
  index.html
Labels: SZM, ok

#61 kérdés fix
  js/script1.js
Labels: SZM, ok

#65 matyi
  Magyar/nevjegy.html
  assets/martin.jpg
Labels: ok

#69 contact
  English/achievements.html
  English/creators.html
  English/mainpage.html
  English/quiz.html
  Magyar/baratai.html
  Magyar/fooldal.html
  Magyar/kviz.html
  Magyar/nevjegy.html
  Magyar/teljesitmenyek.html
Labels: Sz*r

#71 Index.html design
  assets/Képernyőkép 2024-04-09 172605.png
  index.html
Labels: ok

#74 Kvíz oldal reszponzívvé tétele
  English/quiz.html
  Magyar/kviz.html
  css/style1.css
  css/styles.css
Labels: ok

#78 end2
  js/scripts.js
Labels: ok

#82 Kód rendezése
  English/achievements.html
  English/api.json
  English/creators.html
  English/friends.html
  English/mainpage.html
  English/quiz.html
  Magyar/api.json
  Magyar/baratai.html
  Magyar/fooldal.html
  Magyar/kviz.html
  Magyar/nevjegy.html
  Magyar/teljesitmenyek.html
  css/style1.css
  css/styles.css
  index.html
  js/cookie.js
  js/script1.js
  js/scripts.js
Labels: ok

#81 cookie
  English/achievements.html
  English/creators.html
  English/friends.html
  English/mainpage.html
  English/quiz.html
  Magyar/baratai.html
  Magyar/fooldal.html
  Magyar/kviz.html
  Magyar/nevjegy.html
  Magyar/teljesitmenyek.html
  assets/cookie.png
Labels: ok, folyamat

#83 lorem ipsum
  English/creators.html
  Magyar/nevjegy.html
Labels: ok

#84 ppt
  Orbán Viktor.pptx
Labels: help

#86 path átírása relatívra
  English/achievements.html
  English/creators.html
  English/friends.html
  English/mainpage.html
  English/quiz.html
  Magyar/baratai.html
  Magyar/fooldal.html
  Magyar/kviz.html
  Magyar/nevjegy.html
  Magyar/teljesitmenyek.html
  css/styles.css
  index.html
  js/scripts.js
Labels: ok

#87 ppt javítás
  Orbán Viktor.pptx
Labels: ok
